export interface Institution {
  institutionId: string; // auto-generated by backend
  institutionName: string;
  ownershipType: "Public" | "Private" | string;
  institutionType: string; // e.g., "National Polytechnic", "VTC", etc.
  dateOfRegistration?: string; // ISO date string
  physicalAddress: string;
  postalAddress?: string;
  contactInfo: {
    phoneNumbers: string[];
    emails: string[];
    website?: string;
  };
  premises: {
    status: "Owned" | "Leased";
    leaseExpiryDate?: string; // if Leased
    documents?: string[]; // file URLs or IDs referencing uploaded docs
  };
  management: {
    managementType?: string; // "BOG", "BOD", etc.
    strategicPlan?: string; // file URL or ID
    operationalPlan?: string; // file URL or ID
    documentedProcedures?: string;
    qualityManagementSystem?: string;
    members: {
      name: string;
      role: string;
      gender?: string;
      phone?: string;
      email?: string;
      cv?: string; // file URL or ID
    }[];
  };
  infrastructure: {
    classrooms: {
      area: number;
      qualityRating: number; // 1-5 rating
    }[];
    workshops: {
      area: number;
      equipmentQualityRating: number; // 1-5 rating
    }[];
    labs: {
      area: number;
      equipmentQualityRating: number; // 1-5 rating
    }[];
    toilets: {
      countFemale: number;
      countMale: number;
      qualityRating: number;
    };
    waterSource: string;
    solidWasteDisposal: string;
    fireReadiness: number; // 1-5 rating
    safetyFeaturesRating: number; // 1-5 rating
    boardingFacilities?: {
      area: number;
      studentCapacity: number;
      qualityRating: number;
    }[];
    infrastructureInsurance?: boolean;
    insurancePolicyDocs?: string[];
  };
  accreditationStatus?: {
    applicationId: string;
    status: "Pending" | "Under Review" | "Approved" | "Rejected" | "Suspended";
    validUntil?: string; // expiry date if Approved
    certificateUrl?: string;
  };
}
