// src/auth/roles.js
export const ROLES = {
  ADMIN: 'ADMIN',
  REVIEWER: 'REVIEWER',
  INSPECTOR: 'INSPECTOR',
  INSTITUTION: 'INSTITUTION',
  VERIFIER: 'VERIFIER',
  QA_OFFICER: 'QA_OFFICER'
};

export const APPROVAL_LEVELS = {
  DOCUMENT_VERIFICATION: ['VERIFIER', 'QA_OFFICER'],
  INITIAL_REVIEW: ['REVIEWER'],
  TECHNICAL_REVIEW: ['REVIEWER', 'QA_OFFICER'],
  INSPECTION: ['INSPECTOR'],
  FINAL_APPROVAL: ['ADMIN']
};